# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='物资名称')),
                ('type', models.CharField(choices=[('通用测试设备', '通用测试设备'), ('机载测试设备', '机载测试设备'), ('改装装机设备', '改装装机设备'), ('一般耗材', '一般耗材'), ('电连接器', '电连接器'), ('改装标准件', '改装标准件'), ('非标件', '非标件'), ('成品线缆', '成品线缆'), ('系统物资', '系统物资')], max_length=30, verbose_name='物资类型')),
                ('modelNum', models.CharField(max_length=30, verbose_name='物资型号')),
                ('roomNum', models.CharField(max_length=30, verbose_name='库房编号')),
                ('state', models.CharField(choices=[('在库', '在库'), ('出库', '出库'), ('送校', '送校'), ('故障', '故障'), ('停用', '停用')], max_length=30, verbose_name='库存状态')),
                ('number', models.CharField(max_length=10, verbose_name='库存数量')),
                ('location', models.CharField(max_length=100, verbose_name='存放地点')),
                ('department', models.CharField(max_length=30, verbose_name='维护科室')),
                ('meteringNum', models.CharField(max_length=30, verbose_name='计量编号')),
                ('useLife', models.CharField(max_length=30, verbose_name='有效期限')),
                ('serialNum', models.CharField(max_length=30, verbose_name='出厂编号')),
                ('countingUnit', models.CharField(max_length=30, verbose_name='计数单位')),
                ('coreNum', models.CharField(max_length=10, verbose_name='芯数')),
                ('measurement', models.CharField(max_length=30, verbose_name='度量单位')),
                ('mountingNum', models.CharField(max_length=30, verbose_name='装机件号')),
                ('threshold', models.CharField(max_length=10, verbose_name='阈值')),
                ('remarks', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='物资名称')),
                ('type', models.CharField(choices=[('通用测试设备', '通用测试设备'), ('机载测试设备', '机载测试设备'), ('改装装机设备', '改装装机设备'), ('一般耗材', '一般耗材'), ('电连接器', '电连接器'), ('改装标准件', '改装标准件'), ('非标件', '非标件'), ('成品线缆', '成品线缆'), ('系统物资', '系统物资')], max_length=30, verbose_name='物资类型')),
                ('modelNum', models.CharField(max_length=30, verbose_name='物资型号')),
                ('roomNum', models.CharField(max_length=30, verbose_name='库房编号')),
                ('state', models.CharField(choices=[('在库', '在库'), ('出库', '出库'), ('送校', '送校'), ('故障', '故障'), ('停用', '停用')], max_length=30, verbose_name='库存状态')),
                ('number', models.CharField(max_length=10, verbose_name='库存数量')),
                ('location', models.CharField(max_length=100, verbose_name='存放地点')),
                ('department', models.CharField(max_length=30, verbose_name='维护科室')),
                ('meteringNum', models.CharField(max_length=30, verbose_name='计量编号')),
                ('useLife', models.CharField(max_length=30, verbose_name='有效期限')),
                ('serialNum', models.CharField(max_length=30, verbose_name='出厂编号')),
                ('countingUnit', models.CharField(max_length=30, verbose_name='计数单位')),
                ('coreNum', models.CharField(max_length=10, verbose_name='芯数')),
                ('measurement', models.CharField(max_length=30, verbose_name='度量单位')),
                ('mountingNum', models.CharField(max_length=30, verbose_name='装机件号')),
                ('threshold', models.CharField(max_length=10, verbose_name='阈值')),
                ('remarks', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('jobNum', models.CharField(max_length=30, verbose_name='工号')),
                ('department', models.CharField(max_length=30, verbose_name='科室')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=30, verbose_name='电话')),
                ('password', models.CharField(default='123456', max_length=30, verbose_name='密码')),
                ('remarks', models.TextField(default=None, verbose_name='备注')),
            ],
        ),
    ]
