# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_returnmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objects',
        ),
        migrations.DeleteModel(
            name='ReturnBase',
        ),
    ]
